---
- name: 'Install {{galaxy_flavor}} interactive tours'
  copy:
    src: '{{interactive_tour_list_path}}/'
    dest: '{{galaxy_install_path}}/config/plugins/tours/'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
  ignore_errors: true
  when: not debug|bool

- name: '[DEBUG] Install {{galaxy_flavor}} interactive tours'
  copy:
    src: '{{interactive_tour_list_path}}/'
    dest: '{{galaxy_install_path}}/config/plugins/tours/'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
  when: debug|bool
