---
# handlers file for ansible-role-galaxycloud-tools

- name: restart galaxy
  command: "{{ galaxyctl_bin_path }}/galaxyctl restart galaxy --force"
  ignore_errors: yes

- name: start galaxy
  command: "{{ galaxyctl_bin_path }}/galaxyctl start galaxy --force"
  ignore_errors: yes
  when: ansible_virtualization_type != "docker"
